//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "109.1.18+gf1c41e4+chromium-109.0.5414.120"
#define CEF_VERSION_MAJOR 109
#define CEF_VERSION_MINOR 1
#define CEF_VERSION_PATCH 18
#define CEF_COMMIT_NUMBER 2719
#define CEF_COMMIT_HASH "f1c41e4b1392ef8816171c4d51a2fca308db5501"
// clang-format on

#endif // CefVersion
